- name: Create a Directory to export items to
  file:
    path: /tmp/{{ _appmigration_name }}
    state: directory
    mode: '0777'

- name: Lookup existing k8s secrets
  set_fact:
    current_secrets: "{{ lookup('k8s', api_version='v1', kind='Secret', namespace=_appmigration_namespace) }}"
  when: 
    - resource_name not in "default|deployer|builder|-token"

#- name: check Secrets to Export
#  shell: kubctl get secret --no-headers -n {{ _appmigration_namespace }} | egrep -vi "default|deployer|builder|-token" | awk '{print $1}'
#  register: current_secrets

- name: Export Secrets
  shell: kubctl get secret "{{ item }}" -n {{ _appmigration_namespace }} --export -o yaml > /tmp/{{ _appmigration_name }}/existing-secret-{{ item }}.yml
  with_items: 
    - "{{ current_secrets.stdout_lines }}" 
  when: current_secrets.stdout_lines | length > 0 

- name: Lookup existing k8s ServiceAccounts
  set_fact:
    current_sas: "{{ lookup('k8s', api_version='v1', kind='ServiceAccount', namespace=_appmigration_namespace) }}"
  when: 
    - resource_name not in "default|deployer|builder"

#- name: check ServiceAccounts to Export
#  shell: kubctl get sa --no-headers -n {{ _appmigration_namespace }} | egrep -vi "default|deployer|builder" | awk '{print $1}'
#  register: current_sas

- name: Export ServiceAccount
  shell: kubctl get sa "{{ item }}" -n {{ _appmigration_namespace }} --export -o yaml > /tmp/{{ _appmigration_name }}/existing-sa-{{ item }}.yml
  with_items: 
    - "{{ current_sas.stdout_lines }}" 
  when: current_sas.stdout_lines | length > 0 

- name: Lookup existing k8s ConfigMaps
  set_fact:
    current_cms: "{{ lookup('k8s', api_version='v1', kind='ConfigMap', namespace=_appmigration_namespace) }}"

- name: check ConfigMap to Export
  shell: kubctl get cm --no-headers -n {{ _appmigration_namespace }} | awk '{print $1}'
  register: current_cms

- name: Export ConfigMaps 
  shell: kubctl get cm "{{ item }}" -n {{ _appmigration_namespace }} --export -o yaml > /tmp/{{ _appmigration_name }}/existing-cm-{{ item }}.yml
  with_items: 
    - "{{ current_cms.stdout_lines }}"
  when: current_cms.stdout_lines | length > 0 

- name: check RoleBinding to Export
  shell: kubctl get rolebinding --no-headers -n {{ _appmigration_namespace }} | egrep -vi "admin|deployer|builder" | awk '{print $1}'
  register: current_rbs

- name: Export RoleBindings
  shell: kubctl get rolebinding "{{ item }}" -n {{ _appmigration_namespace }} -o yaml > /tmp/{{ _appmigration_name }}/existing-rb-{{ item }}.yml
  with_items: 
    - "{{ current_rbs.stdout_lines }}" 
  when: 
    - current_rbs.stdout_lines | length > 0

- name: check Service to Export
  shell: kubctl get svc --no-headers -n {{ _appmigration_namespace }} | egrep -vi "default|deployer|builder" | awk '{print $1}'
  register: current_svcs

- name: Export Service
  shell: kubctl get svc "{{ item }}" -n {{ _appmigration_namespace }} --export -o yaml > /tmp/{{ _appmigration_name }}/existing-svc-{{ item }}.yml
  with_items: 
    - "{{ current_svcs.stdout_lines }}"
  when: current_svcs.stdout_lines | length > 0 

- name: check Routes to Export
  shell: kubctl get route --no-headers -n {{ _appmigration_namespace }} | egrep -vi "default|deployer|builder" | awk '{print $1}'
  register: current_routes

- name: Export Routes
  shell: kubctl get route "{{ item }}" -n {{ _appmigration_namespace }} --export -o yaml > /tmp/{{ _appmigration_name }}/existing-route-{{ item }}.yml
  with_items: 
    - "{{ current_routes.stdout_lines }}" 
  when: current_routes.stdout_lines | length > 0 

