apiVersion: rhtconsulting.eapquickstarts.dev/v1alpha1
kind: AppMigration 
metadata:
  name: kitchensink-appmigration
spec:
  # Add fields here
  _appmigration_state: present
  _appmigration_namespace: jws3-kitchensink
  _appmigration_namespace_new: jws5-kitchensink
  _appmigration_name: kitchensink
  _appmigration_runtime_image: registry.redhat.io/jboss-webserver-3/webserver31-tomcat8-openshift 
  _appmigration_runtime_image_tag: latest
  _appmigration_runtime_image_new: registry.redhat.io/jboss-webserver-5/webserver50-tomcat9-openshift 
  _appmigration_runtime_image_tag_new: latest
  _appmigration_exported_resources_dir: "$HOME"
  #_appmigration_exported_resources_dir: "/tmp"
  -appmigration_binary_resources_dir: "/opt/webserver/webapps/"
  _appmigration_app_container_config_resources_dir: "/opt/webserver/conf/"
