apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: appmigrations.rhtconsulting.eapquickstarts.dev
spec:
  group: rhtconsulting.eapquickstarts.dev
  names:
    kind: AppMigration
    listKind: AppMigrationList
    plural: appmigrations
    singular: appmigration
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
